# YAML definition for Appveyor.com continuous integration.
# See http://www.appveyor.com/docs/appveyor-yml

version: '{branch}-{build}'

build:
  project: PDFGen.sln
  verbosity: minimal

skip_tags: true

os:
  - Windows Server 2012 R2

configuration:
  - Debug
  - Release

platform:
  - x64    # 64-bit build
  - win32  # 32-bit build