name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://andredesigna/pdfgen:latest

    steps:
      - uses: actions/checkout@v1
      - name: Build Win32
        run: |
          make clean
          make CC=/usr/lib/mxe/usr/bin/i686-w64-mingw32.static-gcc CLANG_FORMAT=clang-format-10
          cp testprog testprog.exe
      - name: Infer
        run: make clean && infer run --no-progress-bar -- make CFLAGS="-g -Wall -pipe" LFLAGS=""
      - name: Build
        run: make clean && make
      - name: Update coverage statistics
        run: |
          if [[ "${CIRCLE_BRANCH}" == "master" ]] ; then
            ./testprog
            coveralls -i pdfgen.c
          fi
      - name: Test
        run: make clean && scan-build-10 --status-bugs make check CLANG_FORMAT=clang-format-10
      - name: Fuzz Test
        run: make fuzz-check CLANG=clang-10 CLANG_FORMAT=clang-format-10 -j8
      - name: Docs
        run: make docs
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            output.pdf
            pdfgen.h
            pdfgen.o
            doc/html/
            testprog
            testprog.exe

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: make x64
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        make clean
        make testprog CC=cl
    - name: make x86
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
        make clean
        make testprog CC=cl

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
