name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Build Win32
        run: make podman-build-win32
      - name: Infer
        run: make podman-infer
      - name: Build
        run: make podman-build
      - name: Test
        run: make podman-test
      - name: Fuzz Test
        run: make podman-fuzz-check -j8
      - name: Docs
        run: make podman-docs
      - name: Coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          GITHUB_REF: ${{ github.ref }}
        run: make podman-coverage
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdfgen-main-artifacts
          path: |
            output.pdf
            output_encrypted.pdf
            pdfgen.h
            pdfgen.o
            doc/html/
            testprog
            testprog.exe
            coverage-html/

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
    - name: make x64
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        make clean
        make testprog.exe CC=cl
        cp testprog.exe testprog-64.exe
        testprog-64
        cp output.pdf output-win64.pdf
        cp output_encrypted.pdf output_encrypted-win64.pdf
    - name: make x86
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
        make clean
        make testprog.exe CC=cl
        cp testprog.exe testprog-32.exe
        testprog-32
        cp output.pdf output-win32.pdf
        cp output_encrypted.pdf output_encrypted-win32.pdf
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pdfgen-win32-artifacts
        path: |
          output-win32.pdf
          output-win64.pdf
          output_encrypted-win32.pdf
          output_encrypted-win64.pdf
          testprog-32.exe
          testprog-64.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - name: make
      run: |
        make
        make testprog
        LC_ALL=C ./testprog
        cp output.pdf output-macos.pdf
        cp output_encrypted.pdf output_encrypted-macos.pdf
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pdfgen-macos-artifacts
        path: |
          output-macos.pdf
          output_encrypted-macos.pdf
          testprog
