name: Submit to Coverity

on:
 push:
    branches:
      - master [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Coverity Tool
        run: |
          wget https://scan.coverity.com/download/cxx/linux64 --post-data "token=$TOKEN&project=AndreRenaud/PDFGen" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xfz cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
      - name: Build
        run: ./cov-analysis-linux64/bin/cov-build --dir cov-int make
      - name: Submit to Coverity
        run: |
          tar czvf pdfgen.tgz cov-int
          curl \
            --form project=AndreRenaud/PDFGen \
            --form token=$TOKEN \
            --form email=andre@ignavus.net \
            --form file=@pdfgen.tgz \
            --form version=master \
            --form description="$GITHUB_SHA" \
            https://scan.coverity.com/builds?project=AndreRenaud/PDFGen
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
